module.exports.docusignMessages = {
  CREATE_SUCCESS: "Contract sent/created successfully ",
  CREATE_ERROR: "Unable to send contract",
  FETCH_SUCCESS: "contracts successfully fetched",
  NONE_FOUND: "No contract found",
  CONTRACT_ERROR: "unable to get contract",
  FETCH_ERROR: "Unable to fetch contract/document",
  UPGRADE_SUCCESSFUL: "contract upgrade successful",
  DUPLICATE: "duplicate contract",
  UPDATE_SUCCESS: "update successful",
  SUCCESS: "successful",
  NO_DATA: "no data receive from docusign",
  ERROR_FILE: "error writing file",
  DOWNLOAD_BASE64: "Document successfully saved as Base64 in a file",
}
